services:
  frontend-container:
    build:
      context: ./frontend
    environment:
      - ./frontend/.env
    ports:
       - "8001:80"
    networks:
       - bridge


  backend-container:
    build:
      context: ./backend
    environment:
      - ./backend/.env
    ports:
       - "10000:10000"
    networks:
      - bridge


  database-container:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-database:/var/lib/postgresql/18/docker
    networks:
      - bridge


volumes:
  postgres-database:

networks:
  bridge:

